import React, { useEffect, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { api } from '../services/api';
import { continueWithGithub } from '../services/github';
import { useAuth } from '../hooks/useAuth';
import Toast from '../components/Toast';
function fmt(s){const m=Math.floor(s/60),r=s%60;return `${m}:${String(r).padStart(2,'0')}`;}
export default function Register(){
  const [q]=useSearchParams();const locked=q.get('email')||'';const needVerify=q.get('verify')||'';
  const [email,setEmail]=useState(needVerify||locked);const [name,setName]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [err,setErr]=useState(needVerify?'✉️ Please verify — fresh code sent! Enter it below.':'');
  const [step,setStep]=useState(needVerify?2:1);const [code,setCode]=useState('');const [left,setLeft]=useState(600);const [cool,setCool]=useState(needVerify?60:0);const [devCode,setDevCode]=useState('');
  const {setToken}=useAuth();const nav=useNavigate();
  useEffect(()=>{if(step!==2)return;setLeft(600);const t=setInterval(()=>setLeft(s=>Math.max(0,s-1)),1000);return ()=>clearInterval(t);},[step]);
  useEffect(()=>{if(cool<=0)return;const t=setInterval(()=>setCool(s=>Math.max(0,s-1)),1000);return ()=>clearInterval(t);},[cool]);
  async function submit(e){e.preventDefault();setErr('');if(!email||password.length<6||!name){setErr('🧑 Name, valid 📧 email and 6+ char 🔑 password required.');return;}try{const r=await api('/auth/register',{method:'POST',body:JSON.stringify({email,name,password})});if(r.devCode)setDevCode(r.devCode);setStep(2);setCool(60);}catch(e){setErr(e.message);}}
  async function verify(e){e?.preventDefault();setErr('');const digits=code.replace(/\D/g,'');if(digits.length!==6){setErr('🔍 Enter the 6-digit code from your email. ✉️');return;}try{const r=await api('/auth/verify',{method:'POST',body:JSON.stringify({email,code:digits})});setToken(r.token);nav('/profile?welcome=1');}catch(e){setErr(e.message);}}
  async function resend(){setErr('');try{const r=await api('/auth/resend-code',{method:'POST',body:JSON.stringify({email})});if(r.devCode)setDevCode(r.devCode);setLeft(600);setCool(60);setErr('');}catch(e){setErr(e.message);}}
  if(step===2) return (<div className="auth-wrap"><div className="card auth-card" style={{textAlign:'center'}}><div style={{fontSize:'2rem'}}>✉️</div><h2>Check your email!</h2><p className="muted">We sent a 6-digit code to <strong>{email}</strong> ⏱️ expires in <strong>{fmt(left)}</strong>.</p><Toast msg={err}/>{devCode&&<p className="pill pending">🧪 Dev code (no SMTP): <strong>{devCode}</strong></p>}<form onSubmit={verify}><div className="field"><label>🔢 6-digit code<input value={code} onChange={e=>setCode(e.target.value.replace(/[^\d]/g,'').slice(0,6))} placeholder="123456" inputMode="numeric" autoFocus style={{textAlign:'center',fontSize:'1.4rem',letterSpacing:6}}/></label></div><button className="btn secondary" type="submit" style={{width:'100%',justifyContent:'center'}}>✅ Verify & continue</button></form><p><button className="btn small ghost" onClick={resend} disabled={cool>0}>📨 {cool>0?`Resend in ${cool}s`:'Resend code'}</button> <button className="btn small ghost" onClick={()=>setStep(1)}>✏️ Wrong email? Edit</button></p></div></div>);
  return (<div className="auth-wrap"><div className="card auth-card"><div style={{fontSize:'2rem'}}>✏️</div><h2>Join FairShare 🎓</h2>{locked&&<p className="pill">🔒 Invite-locked email: {locked}</p>}<Toast msg={err}/><form onSubmit={submit}><div className="field"><label>🧑 Your name<input value={name} onChange={e=>setName(e.target.value)} required placeholder="Ada Lovelace"/></label></div><div className="field"><label>📧 Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required disabled={!!locked}/></label>{locked&&<span className="help">🔒 Locked by your invite — ask the creator to resend to change it.</span>}</div><div className="field"><label>🔑 Password<input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required placeholder="6+ characters"/></label><button type="button" className="btn small ghost" onClick={()=>setShow(!show)}>{show?'🙈 Hide':'👁️ Show'}</button></div><button className="btn secondary" type="submit" style={{marginTop:12,width:'100%',justifyContent:'center'}}>📨 Send verification code</button></form><p style={{textAlign:'center'}} className="muted">— or —</p><button className="btn ghost" type="button" style={{width:'100%',justifyContent:'center'}} onClick={async()=>{setErr('');try{await continueWithGithub(locked);}catch(e){setErr(e.message);}}}>🐙 Continue with GitHub{locked?' (links invite 🔗)':''}</button>{locked&&<p className="help">💡 GitHub email differing from invite? We auto-link by @login 🤝 so you still join the team.</p>}<p>Have an account? <Link to="/login">🔑 Login</Link></p></div></div>);
}
